// {{BLOCK_TITLE}} editor component.
// Generated by `pnpm dailyos:new-block --template composite {{BLOCK_NAME}}`.
// Mirrors v1.4.2 W4-F + Packet B V1.1.1 §5.2 reloadTrigger pattern:
// full `reload` callback dep list to preserve manual-reload correctness;
// separate `reloadTrigger` derived string gates the useEffect to avoid
// the auto-reload loop on success-path attribute writes.

( function () {
	const { registerBlockType } = wp.blocks;
	const { useBlockProps } = wp.blockEditor;
	const { useState, useEffect, useCallback } = wp.element;
	const { __ } = wp.i18n;
	const apiFetch = wp.apiFetch;

	const BLOCK_NAME = 'dailyos/{{BLOCK_NAME}}';

	function {{BLOCK_TITLE_PASCAL}}Edit( props ) {
		const { attributes, setAttributes } = props;
		const blockProps = useBlockProps();
		const [ preview, setPreview ] = useState( null );
		const [ isLoading, setIsLoading ] = useState( false );
		const [ error, setError ] = useState( null );

		const reload = useCallback( () => {
			if ( ! attributes.composition_id ) {
				setPreview( null );
				return;
			}
			setIsLoading( true );
			setError( null );
			apiFetch( {
				path: '/dailyos/v1/{{BLOCK_NAME}}/preview',
				method: 'POST',
				data: {
					composition_id: attributes.composition_id,
					composition_version: attributes.composition_version || 0,
					cache_hint_token: attributes.cache_hint_token || '',
				},
			} )
				.then( ( response ) => {
					setPreview( response );
					if ( response && response.projection ) {
						setAttributes( {
							composition_version:
								response.projection.composition_version ||
								attributes.composition_version,
							watermarks: response.projection.watermarks || {},
							cache_hint_token: response.cache_hint_token || '',
						} );
					}
				} )
				.catch( () => {
					setError(
						__(
							"Something didn't line up. Verify before acting.",
							'dailyos'
						)
					);
				} )
				.finally( () => setIsLoading( false ) );
		}, [ attributes.composition_id, attributes.composition_version, attributes.cache_hint_token, setAttributes ] );

		// Packet B V1.1.1 §5.2 derived trigger — fires reload ONLY on
		// composition_id transitioning to non-empty. Success-path
		// setAttributes writes to composition_version/cache_hint_token
		// don't change reloadTrigger → no auto-reload loop.
		const reloadTrigger = `${ attributes.composition_id ? '1' : '0' }`;
		// eslint-disable-next-line react-hooks/exhaustive-deps -- intentional:
		// reload's identity is recomputed every render via its full dep list;
		// the auto-reload gate is the derived reloadTrigger string per
		// L0 Packet B V1.1 §5.2.
		useEffect( () => { reload(); }, [ reloadTrigger ] );

		return wp.element.createElement(
			'div',
			blockProps,
			wp.element.createElement(
				'button',
				{
					type: 'button',
					onClick: reload,
					disabled: isLoading,
					className: 'dailyos-{{BLOCK_NAME}}-reload',
				},
				isLoading
					? __( 'Loading…', 'dailyos' )
					: __( 'Reload from runtime', 'dailyos' )
			),
			error && wp.element.createElement( 'p', { className: 'dailyos-error' }, error ),
			preview &&
				preview.html &&
				preview.projection &&
				wp.element.createElement( 'div', {
					className: 'dailyos-preview',
					dangerouslySetInnerHTML: { __html: preview.html },
				} )
		);
	}

	registerBlockType( BLOCK_NAME, {
		edit: {{BLOCK_TITLE_PASCAL}}Edit,
		save: () => null,
	} );
} )();
