<?php
/**
 * Score Band block server-side render.
 *
 * Generated by `pnpm dailyos:new-block --template simple score-band`.
 * Mirrors the v1.4.2 W4-F single-fetch + Packet B V1.1.1 typed-error
 * switch contract. Do NOT add a second runtime call in this file —
 * `account_overview_preview` is the cautionary tale (PR #298).
 *
 * @package DailyOS
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	return '';
}

if ( ! function_exists( 'dailyos_score_band_render' ) ) {
	/**
	 * Render the Score Band block from attributes. One runtime call per
	 * render, typed-error switch from Packet B V1.1.1.
	 *
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return string
	 */
	function dailyos_score_band_render( array $attributes ): string {
		$composition_id      = isset( $attributes['composition_id'] ) ? (string) $attributes['composition_id'] : '';
		$composition_version = isset( $attributes['composition_version'] ) ? (int) $attributes['composition_version'] : 0;
		$cache_hint_token    = isset( $attributes['cache_hint_token'] ) ? (string) $attributes['cache_hint_token'] : '';

		if ( '' === $composition_id ) {
			return '<div class="wp-block-dailyos-score-band is-empty">'
				. esc_html__( 'No content to show here.', 'dailyos' )
				. '</div>';
		}

		$runtime_client = apply_filters( 'dailyos_runtime_client_for_block', null );
		if ( ! is_object( $runtime_client ) || ! method_exists( $runtime_client, 'project_composition_for_surface' ) ) {
			return '<div class="wp-block-dailyos-score-band is-empty">'
				. esc_html__( 'No content to show here.', 'dailyos' )
				. '</div>';
		}

		$cache_hint_param = '' !== $cache_hint_token ? $cache_hint_token : null;
		$response         = $runtime_client->project_composition_for_surface(
			$composition_id,
			$composition_version,
			$cache_hint_param
		);

		return dailyos_score_band_render_from_projection( $response, $attributes );
	}

	/**
	 * Pure projection-to-HTML helper. Accepts WP_Error, runtime envelope,
	 * or success-response shapes. Typed-error switch per Packet B V1.1.1.
	 *
	 * @param mixed                $response   Runtime response or WP_Error.
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return string
	 */
	function dailyos_score_band_render_from_projection( $response, array $attributes ): string {
		if ( is_wp_error( $response ) ) {
			return dailyos_score_band_render_runtime_unavailable_notice();
		}

		if ( isset( $response['ok'] ) && false === $response['ok'] ) {
			$code = isset( $response['error']['code'] ) ? (string) $response['error']['code'] : 'runtime_request_failed';
			switch ( $code ) {
				case 'rate_limited':
				case 'transport_abuse_limited':
					return dailyos_score_band_render_throttled_notice();
				case 'session_requires_repair':
				case 'session_not_found':
				case 'session_expired':
				case 'session_throttled':
				case 'session_invalid':
				case 'identity_mismatch':
				case 'wp_user_mismatch':
				case 'pairing_code_invalid':
				case 'pairing_code_expired':
				case 'pairing_code_consumed':
				case 'pairing_code_limited':
				case 'pairing_suspended':
				case 'pairing_revoked':
				case 'pairing_expired':
				case 'pairing_authority_unavailable':
				case 'site_binding_mismatch':
				case 'restored_stale_pairing':
				case 'unknown_runtime_anchor':
				case 'scope_denied':
				case 'auth_missing':
				case 'signature_invalid':
				case 'canonicalization_mismatch':
				case 'timestamp_stale':
				case 'timestamp_future':
				case 'key_not_found':
				case 'key_rotated':
				case 'token_invalid':
				case 'nonce_replay':
					return dailyos_score_band_render_session_repair_notice();
				case 'runtime_unavailable':
				case 'runtime_request_failed':
				case 'runtime_invalid_json':
				case 'runtime_http_error':
				case 'host_invalid':
				case 'browser_origin_forbidden':
				case 'route_not_found':
					return dailyos_score_band_render_runtime_unavailable_notice();
				case 'request_body_too_large':
				case 'request_body_unreadable':
				case 'handshake_body_invalid':
				case 'session_refresh_body_invalid':
				case 'surface_invoke_invalid':
				case 'event_log_id_invalid':
				case 'project_composition_invalid':
				case 'project_composition_unknown_producer':
				case 'project_composition_invalid_id':
					return dailyos_score_band_render_invalid_request_notice();
				case 'projection_tampered':
				case 'projection_version_rollback':
				case 'stale_composition_watermark':
				case 'missing_expected_claim_version':
				case 'mid_flight_mutation':
				case 'composition_version_overflow':
					return dailyos_score_band_render_verification_banner();
				default:
					return dailyos_score_band_render_verification_banner();
			}
		}

		$projection = isset( $response['projection'] ) && is_array( $response['projection'] )
			? $response['projection']
			: null;
		if ( null === $projection ) {
			return dailyos_score_band_render_verification_banner();
		}

		$blocks = isset( $projection['blocks'] ) && is_array( $projection['blocks'] )
			? $projection['blocks']
			: [];

		$wrapper_attrs = function_exists( 'get_block_wrapper_attributes' )
			? get_block_wrapper_attributes(
				[
					'class'        => 'wp-block-dailyos-score-band',
					'data-ds-tier' => 'pattern',
					'data-ds-name' => 'ScoreBand',
				]
			)
			: 'class="wp-block-dailyos-score-band"';

		$out = '<section ' . $wrapper_attrs . '>';

		foreach ( $blocks as $block ) {
			if ( ! is_array( $block ) ) {
				continue;
			}
			$payload = isset( $block['payload'] ) && is_array( $block['payload'] ) ? $block['payload'] : [];
			$text    = isset( $payload['text'] ) && is_string( $payload['text'] ) ? esc_html( (string) $payload['text'] ) : '';
			$trust   = isset( $block['trust_band'] ) ? (string) $block['trust_band'] : 'needs_verification';

			$out .= '<article class="dailyos-block dailyos-block-score-band">';
			$out .= '<span data-ds-tier="primitive" data-ds-name="TrustBandBadge" data-ds-trust-band="' . esc_attr( $trust ) . '"></span>';
			if ( '' !== $text ) {
				$out .= '<p>' . $text . '</p>';
			}
			$out .= '</article>';
		}

		if ( empty( $blocks ) ) {
			$out .= '<p class="dailyos-empty">' . esc_html__( 'No content to show here.', 'dailyos' ) . '</p>';
		}

		$out .= '</section>';

		return $out;
	}

	function dailyos_score_band_render_throttled_notice(): string {
		return '<aside class="dailyos-notice dailyos-throttled">'
			. '<p>' . esc_html__( 'Runtime is throttling; retry shortly.', 'dailyos' ) . '</p>'
			. '</aside>';
	}

	function dailyos_score_band_render_session_repair_notice(): string {
		return '<aside class="dailyos-notice dailyos-session-repair">'
			. '<p>' . esc_html__( 'Surface session needs repair; reconnect from DailyOS settings.', 'dailyos' ) . '</p>'
			. '</aside>';
	}

	function dailyos_score_band_render_runtime_unavailable_notice(): string {
		return '<aside class="dailyos-notice dailyos-runtime-unavailable">'
			. '<p>' . esc_html__( 'Runtime unavailable; retry.', 'dailyos' ) . '</p>'
			. '</aside>';
	}

	function dailyos_score_band_render_invalid_request_notice(): string {
		return '<aside class="dailyos-notice dailyos-invalid-request">'
			. '<p>' . esc_html__( "Editor sent a request the runtime couldn't process. Reload the editor.", 'dailyos' ) . '</p>'
			. '</aside>';
	}

	function dailyos_score_band_render_verification_banner(): string {
		return '<aside data-ds-tier="pattern" data-ds-name="ConsistencyFindingBanner" class="dailyos-verification-banner">'
			. '<p>' . esc_html__( "Something about this content doesn't line up. Verify before acting.", 'dailyos' ) . '</p>'
			. '</aside>';
	}
}
