<?php
/**
 * Status Dot block server-side render.
 *
 * Generated by `pnpm dailyos:new-block --template simple status-dot`.
 * Mirrors the v1.4.2 W4-F single-fetch + Packet B V1.1.1 typed-error
 * switch contract. Do NOT add a second runtime call in this file —
 * `account_overview_preview` is the cautionary tale (PR #298).
 *
 * @package DailyOS
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	return '';
}

if ( ! function_exists( 'dailyos_status_dot_render' ) ) {
	/**
	 * Render the Status Dot block from attributes. One runtime call per
	 * render, typed-error switch from Packet B V1.1.1.
	 *
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return string
	 */
	function dailyos_status_dot_render( array $attributes ): string {
		$composition_id      = isset( $attributes['composition_id'] ) ? (string) $attributes['composition_id'] : '';
		$composition_version = isset( $attributes['composition_version'] ) ? (int) $attributes['composition_version'] : 0;
		$cache_hint_token    = isset( $attributes['cache_hint_token'] ) ? (string) $attributes['cache_hint_token'] : '';

		if ( '' === $composition_id ) {
			return '<div class="wp-block-dailyos-status-dot is-empty">'
				. esc_html__( 'No content to show here.', 'dailyos' )
				. '</div>';
		}

		$runtime_client = apply_filters( 'dailyos_runtime_client_for_block', null );
		if ( ! is_object( $runtime_client ) || ! method_exists( $runtime_client, 'project_composition_for_surface' ) ) {
			return '<div class="wp-block-dailyos-status-dot is-empty">'
				. esc_html__( 'No content to show here.', 'dailyos' )
				. '</div>';
		}

		$cache_hint_param = '' !== $cache_hint_token ? $cache_hint_token : null;
		$response         = $runtime_client->project_composition_for_surface(
			$composition_id,
			$composition_version,
			$cache_hint_param
		);

		return dailyos_status_dot_render_from_projection( $response, $attributes );
	}

	/**
	 * Pure projection-to-HTML helper. Accepts WP_Error, runtime envelope,
	 * or success-response shapes. Typed-error switch per Packet B V1.1.1.
	 *
	 * @param mixed                $response   Runtime response or WP_Error.
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return string
	 */
	function dailyos_status_dot_render_from_projection( $response, array $attributes ): string {
		if ( is_wp_error( $response ) ) {
			return dailyos_status_dot_render_runtime_unavailable_notice();
		}

		if ( isset( $response['ok'] ) && false === $response['ok'] ) {
			$code = isset( $response['error']['code'] ) ? (string) $response['error']['code'] : 'runtime_request_failed';
			switch ( $code ) {
				case 'rate_limited':
				case 'transport_abuse_limited':
					return dailyos_status_dot_render_throttled_notice();
				case 'session_requires_repair':
				case 'session_not_found':
				case 'session_expired':
				case 'session_throttled':
				case 'session_invalid':
				case 'identity_mismatch':
				case 'wp_user_mismatch':
				case 'pairing_code_invalid':
				case 'pairing_code_expired':
				case 'pairing_code_consumed':
				case 'pairing_code_limited':
				case 'pairing_suspended':
				case 'pairing_revoked':
				case 'pairing_expired':
				case 'pairing_authority_unavailable':
				case 'site_binding_mismatch':
				case 'restored_stale_pairing':
				case 'unknown_runtime_anchor':
				case 'scope_denied':
				case 'auth_missing':
				case 'signature_invalid':
				case 'canonicalization_mismatch':
				case 'timestamp_stale':
				case 'timestamp_future':
				case 'key_not_found':
				case 'key_rotated':
				case 'token_invalid':
				case 'nonce_replay':
					return dailyos_status_dot_render_session_repair_notice();
				case 'runtime_unavailable':
				case 'runtime_request_failed':
				case 'runtime_invalid_json':
				case 'runtime_http_error':
				case 'host_invalid':
				case 'browser_origin_forbidden':
				case 'route_not_found':
					return dailyos_status_dot_render_runtime_unavailable_notice();
				case 'request_body_too_large':
				case 'request_body_unreadable':
				case 'handshake_body_invalid':
				case 'session_refresh_body_invalid':
				case 'surface_invoke_invalid':
				case 'event_log_id_invalid':
				case 'project_composition_invalid':
				case 'project_composition_unknown_producer':
				case 'project_composition_invalid_id':
					return dailyos_status_dot_render_invalid_request_notice();
				case 'projection_tampered':
				case 'projection_version_rollback':
				case 'stale_composition_watermark':
				case 'missing_expected_claim_version':
				case 'mid_flight_mutation':
				case 'composition_version_overflow':
					return dailyos_status_dot_render_verification_banner();
				default:
					return dailyos_status_dot_render_verification_banner();
			}
		}

		$projection = isset( $response['projection'] ) && is_array( $response['projection'] )
			? $response['projection']
			: null;
		if ( null === $projection ) {
			return dailyos_status_dot_render_verification_banner();
		}

		$block = dailyos_status_dot_select_projected_block( $projection, $attributes );
		if ( null === $block ) {
			return '<div class="wp-block-dailyos-status-dot is-empty">'
				. esc_html__( 'No content to show here.', 'dailyos' )
				. '</div>';
		}

		$payload = isset( $block['payload'] ) && is_array( $block['payload'] ) ? $block['payload'] : [];
		$values  = isset( $payload['payload'] ) && is_array( $payload['payload'] ) ? $payload['payload'] : $payload;
		$state   = dailyos_status_dot_normalize_state( dailyos_status_dot_string_value( $values, 'status', dailyos_status_dot_string_value( $values, 'state', 'connected' ) ) );
		$size    = dailyos_status_dot_normalize_size( dailyos_status_dot_string_value( $values, 'size', 'md' ) );
		$label   = dailyos_status_dot_string_value( $values, 'label', dailyos_status_dot_string_value( $values, 'text', '' ) );
		$aria    = '' !== $label ? $label : $state;

		$classes = [
			'dailyos-status-dot',
			'dailyos-status-dot--' . $state,
			'dailyos-status-dot--size-' . $size,
		];

		$out = sprintf(
			'<span class="%s" role="img" aria-label="%s" data-ds-tier="primitive" data-ds-name="StatusDot" data-ds-spec="primitives/StatusDot.md"></span>',
			esc_attr( implode( ' ', $classes ) ),
			esc_attr( $aria )
		);

		if ( '' !== $label ) {
			$out .= '<span class="dailyos-status-dot__label">' . esc_html( $label ) . '</span>';
		}

		return $out;
	}

	/**
	 * Select the projected block this primitive instance should render.
	 *
	 * @param array<string, mixed> $projection Projected composition.
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return array<string, mixed>|null
	 */
	function dailyos_status_dot_select_projected_block( array $projection, array $attributes ): ?array {
		$blocks = isset( $projection['blocks'] ) && is_array( $projection['blocks'] )
			? $projection['blocks']
			: [];
		if ( empty( $blocks ) ) {
			return null;
		}

		$block_id = isset( $attributes['block_id'] ) ? (string) $attributes['block_id'] : '';
		if ( '' !== $block_id ) {
			foreach ( $blocks as $block ) {
				if ( is_array( $block ) && isset( $block['block_id'] ) && $block_id === (string) $block['block_id'] ) {
					return $block;
				}
			}
		}

		foreach ( $blocks as $block ) {
			if ( is_array( $block ) ) {
				return $block;
			}
		}

		return null;
	}

	/**
	 * Read a string payload field.
	 *
	 * @param array<string, mixed> $values  Payload values.
	 * @param string               $key     Field key.
	 * @param string               $default Fallback value.
	 * @return string
	 */
	function dailyos_status_dot_string_value( array $values, string $key, string $default ): string {
		return isset( $values[ $key ] ) && is_string( $values[ $key ] ) ? trim( $values[ $key ] ) : $default;
	}

	/**
	 * Coerce arbitrary state string to a supported status-dot state value.
	 *
	 * @param string $state Raw state string from payload.
	 * @return string
	 */
	function dailyos_status_dot_normalize_state( string $state ): string {
		return in_array( $state, [ 'connected', 'disconnected', 'loading', 'error' ], true ) ? $state : 'connected';
	}

	/**
	 * Coerce arbitrary size string to a supported status-dot size token.
	 *
	 * @param string $size Raw size string from payload.
	 * @return string
	 */
	function dailyos_status_dot_normalize_size( string $size ): string {
		return in_array( $size, [ 'sm', 'md' ], true ) ? $size : 'md';
	}

	/**
	 * Render the throttled-runtime notice fragment for the status-dot block.
	 */
	function dailyos_status_dot_render_throttled_notice(): string {
		return '<aside class="dailyos-notice dailyos-throttled">'
			. '<p>' . esc_html__( 'Runtime is throttling; retry shortly.', 'dailyos' ) . '</p>'
			. '</aside>';
	}

	/**
	 * Render the session-repair notice fragment for the status-dot block.
	 */
	function dailyos_status_dot_render_session_repair_notice(): string {
		return '<aside class="dailyos-notice dailyos-session-repair">'
			. '<p>' . esc_html__( 'Surface session needs repair; reconnect from DailyOS settings.', 'dailyos' ) . '</p>'
			. '</aside>';
	}

	/**
	 * Render the runtime-unavailable notice fragment for the status-dot block.
	 */
	function dailyos_status_dot_render_runtime_unavailable_notice(): string {
		return '<aside class="dailyos-notice dailyos-runtime-unavailable">'
			. '<p>' . esc_html__( 'Runtime unavailable; retry.', 'dailyos' ) . '</p>'
			. '</aside>';
	}

	/**
	 * Render the invalid-request notice fragment for the status-dot block.
	 */
	function dailyos_status_dot_render_invalid_request_notice(): string {
		return '<aside class="dailyos-notice dailyos-invalid-request">'
			. '<p>' . esc_html__( "Editor sent a request the runtime couldn't process. Reload the editor.", 'dailyos' ) . '</p>'
			. '</aside>';
	}

	/**
	 * Render the consistency-finding verification banner for the status-dot block.
	 */
	function dailyos_status_dot_render_verification_banner(): string {
		return '<aside data-ds-tier="pattern" data-ds-name="ConsistencyFindingBanner" class="dailyos-verification-banner">'
			. '<p>' . esc_html__( "Something about this content doesn't line up. Verify before acting.", 'dailyos' ) . '</p>'
			. '</aside>';
	}
}
