<?php
/**
 * Provenance Tag block server-side render.
 *
 * Generated by `pnpm dailyos:new-block --template primitive-inline provenance-tag`.
 * Mirrors the v1.4.2 W4-F single-fetch + Packet B V1.1.1 typed-error
 * switch contract. Do NOT add a second runtime call in this file -
 * `account_overview_preview` is the cautionary tale (PR #298).
 *
 * @package DailyOS
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	return '';
}

if ( ! function_exists( 'dailyos_provenance_tag_render' ) ) {
	/**
	 * Render the Provenance Tag block from attributes. One runtime call per
	 * render, typed-error switch from Packet B V1.1.1.
	 *
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return string
	 */
	function dailyos_provenance_tag_render( array $attributes ): string {
		$composition_id      = isset( $attributes['composition_id'] ) ? (string) $attributes['composition_id'] : '';
		$composition_version = isset( $attributes['composition_version'] ) ? (int) $attributes['composition_version'] : 0;
		$cache_hint_token    = isset( $attributes['cache_hint_token'] ) ? (string) $attributes['cache_hint_token'] : '';

		if ( '' === $composition_id ) {
			return dailyos_provenance_tag_render_empty_primitive();
		}

		$runtime_client = apply_filters( 'dailyos_runtime_client_for_block', null );
		if ( ! is_object( $runtime_client ) || ! method_exists( $runtime_client, 'project_composition_for_surface' ) ) {
			return dailyos_provenance_tag_render_empty_primitive();
		}

		$cache_hint_param = '' !== $cache_hint_token ? $cache_hint_token : null;
		$response         = $runtime_client->project_composition_for_surface(
			$composition_id,
			$composition_version,
			$cache_hint_param
		);

		return dailyos_provenance_tag_render_from_projection( $response, $attributes );
	}

	/**
	 * Pure projection-to-HTML helper. Accepts WP_Error, runtime envelope,
	 * or success-response shapes. Typed-error switch per Packet B V1.1.1.
	 *
	 * @param mixed                $response   Runtime response or WP_Error.
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return string
	 */
	function dailyos_provenance_tag_render_from_projection( $response, array $attributes ): string {
		if ( is_wp_error( $response ) ) {
			return dailyos_provenance_tag_render_runtime_unavailable_notice();
		}

		if ( isset( $response['ok'] ) && false === $response['ok'] ) {
			$code = isset( $response['error']['code'] ) ? (string) $response['error']['code'] : 'runtime_request_failed';
			switch ( $code ) {
				case 'rate_limited':
				case 'transport_abuse_limited':
					return dailyos_provenance_tag_render_throttled_notice();
				case 'session_requires_repair':
				case 'session_not_found':
				case 'session_expired':
				case 'session_throttled':
				case 'session_invalid':
				case 'identity_mismatch':
				case 'wp_user_mismatch':
				case 'pairing_code_invalid':
				case 'pairing_code_expired':
				case 'pairing_code_consumed':
				case 'pairing_code_limited':
				case 'pairing_suspended':
				case 'pairing_revoked':
				case 'pairing_expired':
				case 'pairing_authority_unavailable':
				case 'site_binding_mismatch':
				case 'restored_stale_pairing':
				case 'unknown_runtime_anchor':
				case 'scope_denied':
				case 'auth_missing':
				case 'signature_invalid':
				case 'canonicalization_mismatch':
				case 'timestamp_stale':
				case 'timestamp_future':
				case 'key_not_found':
				case 'key_rotated':
				case 'token_invalid':
				case 'nonce_replay':
					return dailyos_provenance_tag_render_session_repair_notice();
				case 'runtime_unavailable':
				case 'runtime_request_failed':
				case 'runtime_invalid_json':
				case 'runtime_http_error':
				case 'host_invalid':
				case 'browser_origin_forbidden':
				case 'route_not_found':
					return dailyos_provenance_tag_render_runtime_unavailable_notice();
				case 'request_body_too_large':
				case 'request_body_unreadable':
				case 'handshake_body_invalid':
				case 'session_refresh_body_invalid':
				case 'surface_invoke_invalid':
				case 'event_log_id_invalid':
				case 'project_composition_invalid':
				case 'project_composition_unknown_producer':
				case 'project_composition_invalid_id':
					return dailyos_provenance_tag_render_invalid_request_notice();
				case 'projection_tampered':
				case 'projection_version_rollback':
				case 'stale_composition_watermark':
				case 'missing_expected_claim_version':
				case 'mid_flight_mutation':
				case 'composition_version_overflow':
					return dailyos_provenance_tag_render_verification_banner();
				default:
					return dailyos_provenance_tag_render_verification_banner();
			}
		}

		$projection = isset( $response['projection'] ) && is_array( $response['projection'] )
			? $response['projection']
			: null;
		if ( null === $projection ) {
			return dailyos_provenance_tag_render_verification_banner();
		}

		$block = dailyos_provenance_tag_select_projected_block( $projection, $attributes );
		if ( null === $block ) {
			return dailyos_provenance_tag_render_empty_primitive();
		}

		$payload = isset( $block['payload'] ) && is_array( $block['payload'] ) ? $block['payload'] : [];
		$values  = isset( $payload['payload'] ) && is_array( $payload['payload'] ) ? $payload['payload'] : $payload;

		$source_value = dailyos_provenance_tag_first_value(
			$values,
			[ 'itemSource', 'item_source', 'source', 'dataSource', 'data_source' ]
		);
		$label_value  = dailyos_provenance_tag_first_value(
			$values,
			[ 'sourceLabel', 'source_label', 'label', 'text' ]
		);

		if ( dailyos_provenance_tag_is_synthesis_source( $source_value )
			|| dailyos_provenance_tag_is_synthesis_source( $label_value ) ) {
			return dailyos_provenance_tag_render_empty_primitive( 'dailyos-provenance-tag--synthesis-suppressed' );
		}

		$source_label = dailyos_provenance_tag_source_label( $source_value, $label_value );
		$age_label    = dailyos_provenance_tag_relative_age(
			dailyos_provenance_tag_first_value(
				$values,
				[ 'age', 'asOf', 'as_of', 'sourceAsof', 'source_asof', 'sourcedAt', 'sourced_at', 'observedAt', 'observed_at', 'capturedAt', 'captured_at' ]
			)
		);

		$explicit_variant = dailyos_provenance_tag_normalize_variant(
			dailyos_provenance_tag_string_value( $values, 'variant', '' )
		);
		$discrepancy      = dailyos_provenance_tag_bool_value( $values, 'discrepancy' )
			|| 'discrepancy' === $explicit_variant;
		$variant          = dailyos_provenance_tag_resolve_variant(
			$explicit_variant,
			$source_label,
			$age_label,
			$discrepancy
		);

		if ( '' === $source_label && '' === $age_label ) {
			return dailyos_provenance_tag_render_empty_primitive();
		}

		return dailyos_provenance_tag_render_tag( $source_label, $age_label, $variant, $discrepancy );
	}

	/**
	 * Select the projected block this primitive instance should render.
	 *
	 * @param array<string, mixed> $projection Projected composition.
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return array<string, mixed>|null
	 */
	function dailyos_provenance_tag_select_projected_block( array $projection, array $attributes ): ?array {
		$blocks = isset( $projection['blocks'] ) && is_array( $projection['blocks'] )
			? $projection['blocks']
			: [];
		if ( empty( $blocks ) ) {
			return null;
		}

		$block_id = isset( $attributes['block_id'] ) ? (string) $attributes['block_id'] : '';
		if ( '' !== $block_id ) {
			foreach ( $blocks as $block ) {
				if ( is_array( $block ) && isset( $block['block_id'] ) && $block_id === (string) $block['block_id'] ) {
					return $block;
				}
			}
		}

		foreach ( $blocks as $block ) {
			if ( is_array( $block ) ) {
				return $block;
			}
		}

		return null;
	}

	/**
	 * @param array<string, mixed> $values Payload values.
	 * @param array<int, string>   $keys   Candidate field names.
	 * @return mixed|null
	 */
	function dailyos_provenance_tag_first_value( array $values, array $keys ) {
		foreach ( $keys as $key ) {
			if ( array_key_exists( $key, $values ) && null !== $values[ $key ] && '' !== $values[ $key ] ) {
				return $values[ $key ];
			}
		}
		return null;
	}

	/**
	 * Read a string payload field.
	 *
	 * @param array<string, mixed> $values  Payload values.
	 * @param string               $key     Field key.
	 * @param string               $default Fallback value.
	 * @return string
	 */
	function dailyos_provenance_tag_string_value( array $values, string $key, string $default ): string {
		return isset( $values[ $key ] ) && is_string( $values[ $key ] ) ? trim( $values[ $key ] ) : $default;
	}

	/**
	 * Read a boolean payload field.
	 *
	 * @param array<string, mixed> $values Payload values.
	 * @param string               $key    Field key.
	 * @return bool
	 */
	function dailyos_provenance_tag_bool_value( array $values, string $key ): bool {
		if ( ! array_key_exists( $key, $values ) ) {
			return false;
		}
		$value = $values[ $key ];
		if ( is_bool( $value ) ) {
			return $value;
		}
		if ( is_string( $value ) ) {
			return in_array( strtolower( trim( $value ) ), [ '1', 'true', 'yes', 'on' ], true );
		}
		return is_int( $value ) && 1 === $value;
	}

	/**
	 * @param mixed|null $source_value Raw source enum/object.
	 * @param mixed|null $label_value  Human-readable source label.
	 * @return string
	 */
	function dailyos_provenance_tag_source_label( $source_value, $label_value ): string {
		if ( is_string( $label_value ) && '' !== trim( $label_value ) ) {
			return trim( $label_value );
		}

		if ( is_array( $source_value ) ) {
			$source    = dailyos_provenance_tag_string_value( $source_value, 'source', '' );
			$reference = dailyos_provenance_tag_string_value( $source_value, 'reference', '' );
			if ( 'transcript' === $source ) {
				return '' !== $reference ? 'from meeting ' . $reference : 'from meeting';
			}
			if ( 'local_file' === $source ) {
				return '' !== $reference ? 'from ' . $reference : 'from file';
			}
			return dailyos_provenance_tag_format_source_name( $source );
		}

		return is_string( $source_value ) ? dailyos_provenance_tag_format_source_name( trim( $source_value ) ) : '';
	}

	function dailyos_provenance_tag_format_source_name( string $source ): string {
		if ( '' === $source ) {
			return '';
		}

		switch ( strtolower( $source ) ) {
			case 'pty_synthesis':
				return '';
			case 'glean':
			case 'glean_chat':
				return 'from Glean';
			case 'redacted':
			case 'glean_crm':
				return 'from REDACTED';
			case 'zendesk':
			case 'glean_zendesk':
				return 'from Zendesk';
			case 'gong':
			case 'glean_gong':
				return 'from Gong';
			case 'email':
				return 'from email';
			case 'local_file':
				return 'from file';
			case 'transcript':
				return 'from meeting';
			case 'user_correction':
				return 'you edited this';
			default:
				return dailyos_provenance_tag_title_case_source( $source );
		}
	}

	function dailyos_provenance_tag_title_case_source( string $source ): string {
		$parts = preg_split( '/[_\s-]+/', trim( $source ) ) ?: [];
		$out   = [];
		foreach ( $parts as $part ) {
			if ( '' !== $part ) {
				$out[] = strtoupper( substr( $part, 0, 1 ) ) . substr( $part, 1 );
			}
		}
		return implode( ' ', $out );
	}

	/**
	 * @param mixed|null $value Raw source candidate.
	 * @return bool
	 */
	function dailyos_provenance_tag_is_synthesis_source( $value ): bool {
		if ( is_array( $value ) ) {
			$value = dailyos_provenance_tag_string_value( $value, 'source', '' );
		}
		if ( ! is_string( $value ) ) {
			return false;
		}
		$normalized = strtolower( str_replace( [ '-', ' ' ], '_', trim( $value ) ) );
		return 'pty_synthesis' === $normalized;
	}

	/**
	 * @param mixed|null $value Timestamp or age duration.
	 * @return string
	 */
	function dailyos_provenance_tag_relative_age( $value ): string {
		if ( null === $value || '' === $value ) {
			return '';
		}

		$now = time();
		if ( is_int( $value ) || is_float( $value ) ) {
			$seconds = $value > 1000000000 ? $now - (int) $value : (int) $value;
			return dailyos_provenance_tag_format_duration( $seconds );
		}

		if ( ! is_string( $value ) ) {
			return '';
		}

		$trimmed = trim( $value );
		if ( '' === $trimmed ) {
			return '';
		}

		if ( is_numeric( $trimmed ) ) {
			$numeric  = (float) $trimmed;
			$seconds = $numeric > 1000000000 ? $now - (int) $numeric : (int) $numeric;
			return dailyos_provenance_tag_format_duration( $seconds );
		}

		$timestamp = strtotime( $trimmed );
		if ( false === $timestamp ) {
			return '';
		}

		return dailyos_provenance_tag_format_duration( $now - $timestamp );
	}

	function dailyos_provenance_tag_format_duration( int $seconds ): string {
		$future = $seconds < 0;
		$abs    = abs( $seconds );

		if ( $abs < 60 ) {
			return $future ? 'in less than 1m' : 'just now';
		}

		$units = [
			'y'  => 31536000,
			'mo' => 2592000,
			'w'  => 604800,
			'd'  => 86400,
			'h'  => 3600,
			'm'  => 60,
		];

		foreach ( $units as $suffix => $unit_seconds ) {
			if ( $abs >= $unit_seconds ) {
				$count = (int) floor( $abs / $unit_seconds );
				$label = $count . $suffix;
				return $future ? 'in ' . $label : $label . ' ago';
			}
		}

		return '';
	}

	function dailyos_provenance_tag_normalize_variant( string $variant ): string {
		$normalized = strtolower( str_replace( '_', '-', trim( $variant ) ) );
		return in_array( $normalized, [ 'with-source', 'age-only', 'discrepancy' ], true ) ? $normalized : '';
	}

	function dailyos_provenance_tag_resolve_variant( string $explicit_variant, string $source_label, string $age_label, bool $discrepancy ): string {
		if ( $discrepancy ) {
			return 'discrepancy';
		}
		if ( 'age-only' === $explicit_variant ) {
			return 'age-only';
		}
		if ( '' === $source_label && '' !== $age_label ) {
			return 'age-only';
		}
		return 'with-source';
	}

	function dailyos_provenance_tag_render_tag( string $source_label, string $age_label, string $variant, bool $discrepancy ): string {
		$classes = [
			'dailyos-provenance-tag',
			'dailyos-provenance-tag--' . $variant,
		];
		$pieces = [];

		if ( $discrepancy ) {
			$pieces[] = '<span class="dailyos-provenance-tag__discrepancy-marker" aria-hidden="true">!</span>';
		}
		if ( 'age-only' !== $variant && '' !== $source_label ) {
			$pieces[] = '<span class="dailyos-provenance-tag__source">' . esc_html( $source_label ) . '</span>';
		}
		if ( '' !== $age_label ) {
			$pieces[] = '<span class="dailyos-provenance-tag__age">' . esc_html( $age_label ) . '</span>';
		}

		return sprintf(
			'<span class="%s" data-ds-tier="primitive" data-ds-name="ProvenanceTag" data-ds-spec="primitives/ProvenanceTag.md">%s</span>',
			esc_attr( implode( ' ', $classes ) ),
			implode( '<span class="dailyos-provenance-tag__separator" aria-hidden="true">·</span>', $pieces )
		);
	}

	function dailyos_provenance_tag_render_empty_primitive( string $extra_class = '' ): string {
		$classes = 'dailyos-provenance-tag dailyos-provenance-tag--with-source is-empty';
		if ( '' !== $extra_class ) {
			$classes .= ' ' . $extra_class;
		}
		return '<span class="' . esc_attr( $classes ) . '" data-ds-tier="primitive" data-ds-name="ProvenanceTag" data-ds-spec="primitives/ProvenanceTag.md"></span>';
	}

	function dailyos_provenance_tag_render_inline_notice( string $class, string $message ): string {
		return '<span class="dailyos-provenance-tag dailyos-provenance-tag--with-source dailyos-notice ' . esc_attr( $class ) . '" data-ds-tier="primitive" data-ds-name="ProvenanceTag" data-ds-spec="primitives/ProvenanceTag.md" role="status">'
			. esc_html( $message )
			. '</span>';
	}

	function dailyos_provenance_tag_render_throttled_notice(): string {
		return dailyos_provenance_tag_render_inline_notice(
			'dailyos-throttled',
			__( 'Content is temporarily unavailable.', 'dailyos' )
		);
	}

	function dailyos_provenance_tag_render_session_repair_notice(): string {
		return dailyos_provenance_tag_render_inline_notice(
			'dailyos-session-repair',
			__( 'Reconnect this surface to refresh content.', 'dailyos' )
		);
	}

	function dailyos_provenance_tag_render_runtime_unavailable_notice(): string {
		return dailyos_provenance_tag_render_inline_notice(
			'dailyos-runtime-unavailable',
			__( 'Content is temporarily unavailable.', 'dailyos' )
		);
	}

	function dailyos_provenance_tag_render_invalid_request_notice(): string {
		return dailyos_provenance_tag_render_inline_notice(
			'dailyos-invalid-request',
			__( 'Content cannot render from the current request.', 'dailyos' )
		);
	}

	function dailyos_provenance_tag_render_verification_banner(): string {
		return dailyos_provenance_tag_render_inline_notice(
			'dailyos-verification-banner',
			__( 'Content needs verification before rendering.', 'dailyos' )
		);
	}
}
