<?php
/**
 * Provenance Tag dynamic block render entrypoint.
 *
 * Delegates to the renderer in render-functions.php so the same function
 * services the block-registration render path. Generated by
 * `pnpm dailyos:new-block --template primitive-inline provenance-tag`.
 *
 * @package DailyOS
 *
 * @var array<string, mixed> $attributes Block attributes from core.
 * @var array<string, mixed> $block      Block instance (carries envelopeHandle ctx — DOS-691).
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	return '';
}

if ( ! function_exists( 'dailyos_provenance_tag_render' ) ) {
	require_once __DIR__ . '/render-functions.php';
}

$attributes = isset( $attributes ) && is_array( $attributes ) ? $attributes : [];
$ctx        = [];
if ( isset( $block ) && is_object( $block ) && isset( $block->context ) && is_array( $block->context ) ) {
	$ctx = $block->context;
}
// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- render functions escape output internally via esc_html / esc_attr / wp_kses (W3 contract).
echo dailyos_provenance_tag_render( $attributes, $ctx );
