/**
 * Ability surface inventory format — DOS-546 W1-C.
 *
 * Mirrors `src-tauri/abilities-runtime/src/inventory.rs` and Phase 0
 * artifact 05 (`.docs/plans/dos-546/phase-0/05-ability-surface-inventory.md`).
 * The Rust struct and this interface are the single contract consumed by:
 *
 * - the WordPress plugin's `class-dailyos-ability-registry.php`
 * - the custom MCP server's allowlist
 * - SurfaceClient introspection (`list_tools` filtered by `mcp_exposure`)
 * - Wave 4 block code for renderable abilities
 *
 * The serialized JSON artifact lives at `tools/dailyos-abilities.json`
 * and is regenerated by the `emit_ability_inventory` binary. CI gates
 * drift via `scripts/check_ability_inventory.sh`.
 *
 * ## Additive-only contract
 *
 * Per W1-C acceptance criteria, the schema is additive-only across
 * consuming releases. Future fields land as `?` optional, never as
 * renames or removals; the `schema_version` envelope bumps only on
 * additive extensions.
 */

/** Surface-facing actor classes. Mirrors `AbilityActor` (Rust). */
export type AbilityActor =
  | "user"
  | "runtime"
  | "mcp_client"
  | "surface_client";

/** Behavioral taxonomy. Mirrors ADR-0102 §76-95. */
export type AbilityCategory =
  | "read"
  | "transform"
  | "publish"
  | "maintenance";

/** MCP enumeration tier. */
export type McpExposure = "none" | "metadata_only" | "invocable";

/** Retry / dedup classification. */
export type IdempotencyClass = "idempotent" | "safe_retry" | "side_effect";

/** Known composition block types; `custom` requires
 *  `annotations.custom_block_type`. */
export type CompositionBlockType =
  | "account_overview"
  | "claim_summary"
  | "evidence_list"
  | "health_snapshot"
  | "relationship_map"
  | "risk_callout"
  | "action_list"
  | "markdown_document"
  | "custom";

/** Composition kind discriminator. Matches the canonical artifact 05
 *  shape: either `{ produces_blocks: false, block_types: [] }` or
 *  `{ produces_blocks: true, block_types: [<one or more>] }`. The Rust
 *  side enforces this discriminated union via bespoke serde; the
 *  invalid mixed shape (`produces_blocks: false` with non-empty
 *  `block_types`, or `produces_blocks: true` with empty `block_types`)
 *  is rejected at deserialization. */
export type CompositionKind =
  | { produces_blocks: false; block_types: [] }
  | { produces_blocks: true; block_types: CompositionBlockType[] };

/** Free-form annotation value. Numbers are JSON-native `number` (no
 *  integer/float distinction); the Rust mirror represents the numeric
 *  arm as `f64`. */
export type AnnotationValue = string | number | boolean | null;

/** One inventory entry. Mirrors `AbilitySurfaceInventoryEntry` (Rust). */
export interface AbilitySurfaceInventoryEntry {
  name: string;
  description: string;
  category: AbilityCategory;
  annotations: Record<string, AnnotationValue>;
  wp_permission: string;
  allowed_actors: AbilityActor[];
  required_scopes: string[];
  mcp_exposure: McpExposure;
  client_side_executable: boolean;
  idempotency_class: IdempotencyClass;
  composition_kind: CompositionKind;
}

/** Full inventory artifact envelope. */
export interface AbilitySurfaceInventory {
  schema_version: number;
  abilities: AbilitySurfaceInventoryEntry[];
}

/** Schema version emitted by the current Rust crate. Consumers should
 *  refuse to load inventories with a higher version than they
 *  understand. */
export const ABILITY_SURFACE_INVENTORY_SCHEMA_VERSION = 1 as const;
